Repository debionetwork/pipeline-test, pull requests merged in 2021-11, with the labels that each got.

#2 added pr comment trigger
  .github/workflows/benchmark.yml
Labels: enhancement

#3 update gh runner start
  .github/workflows/main.yml
Labels: duplicate

#4 update pr comment check
  .github/workflows/benchmark.yml
Labels: duplicate

#5 add README.md
  README.md
Labels: documentation

#6 fix needs typo
  .github/workflows/benchmark.yml
Labels: duplicate

#7 update runs-on
  .github/workflows/benchmark.yml
Labels: duplicate
